name 'dvwa'
maintainer '8bitbrad'
maintainer_email 'brad@bljl.net'
license 'MIT'
description 'Installs/Configures dvwa'
long_description 'Installs/Configures dvwa'
version '0.1.0'
issues_url 'https://github.com/8bitbrad/dvwa_chef/issues'
source_url 'https://github.com/8bitbrad/dvwa_chef'
supports 'ubuntu', '= 18.04'
chef_version '~> 14'
depends 'nginx', '~> 9.0.0'
