name 'dvwa'
maintainer '8bitbrad'
maintainer_email 'brad@bljl.net'
license 'MIT'
description 'Installs/Configures dvwa'
long_description 'Installs/Configures dvwa'
version '0.1.0'
# issues_url 'https://github.com/<insert_org_here>/dvwa/issues'
# source_url 'https://github.com/<insert_org_here>/dvwa'
supports 'ubuntu', '= 18.04'
chef_version '~> 14'
depends 'nginx', '~> 9.0.0'
